---

networks:
  fastapi:
    driver: bridge

volumes:
  backend-data:

services:

  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8888:8888"
    restart: unless-stopped
    networks:
      - fastapi
    volumes:
      - backend-data:/backend/app/data:rw

  frontend:
    build: ./frontend
    container_name: fusion-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - fastapi
    volumes:
      #  configure custom nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # configure html
      - ./frontend/Devops_Intern.html:/usr/share/nginx/html/index.html:ro
